name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: kalibrewhan_test
        ports: [ '3306:3306' ]
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent" \
          --health-interval=10s \
          --health-timeout=5s \
          --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql, bcmath
          coverage: none

      - name: Cache Composer deps
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Install Composer deps
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Copy env
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      - name: Set up database
        run: php artisan migrate --force
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: kalibrewhan_test
          DB_USERNAME: root
          DB_PASSWORD: root

      - name: Install Node deps
        run: |
          npm install
          npm run build

      - name: Run tests
        run: php artisan test --testsuite=Unit,Feature --stop-on-failure --no-interaction
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: kalibrewhan_test
          DB_USERNAME: root
          DB_PASSWORD: root
